using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Core.EntityObject
{
    class CLS_Declaracion_Info
    {
        //ENCABEZADOS
        public static string[] labelEncabezados = {
            "DATOS DE IDENTIFICACIÓN",
            "DATOS GENERALES",
            "DETERMINACIÓN DEL IMPUESTO SOBRE LA RENTA",
            "PERSONAS MORALES RÉGIMEN GENERAL",
            "DETALLE DEL PAGO",
            "R1 ISR PERSONAS MORALES",
            "R13 ISR RETENCIONES POR ASIMILADOS A SALARIOS",
            "R14 ISR RETENCIONES POR SERVICIOS PROFESIONALES",
            "R18 ISR RETENCIONES POR PAGOS AL EXTRANJERO",
            "DETERMINACIÓN DEL IMPUESTO AL VALOR AGREGADO",
            "MONTOS DE LOS ACTOS O ACTIVIDADES PAGADOS",
            "DETALLE DEL TOTAL DE LOS ACTOS O ACTIVIDADES PAGADOS A LA TASA DEL 16% DE IVA",
            "DETERMINACIÓN DEL IMPUESTO AL VALOR AGREGADO ACREDITABLE",
            "DETERMINACIÓN DE IMPUESTO AL VALOR AGREGADO",
            "DETALLE DEL VALOR DE LOS ACTOS O ACTIVIDADES GRAVADOS A LA TASA DEL 16%",
            "R21 IMPUESTO AL VALOR AGREGADO", "R24 IVA RETENCIONES"
        };

        public static string[] labelExclusiones =
        {
            "DATOS DE IDENTIFICACIÓN",
            "DATOS GENERALES",
            "DETERMINACIÓN DEL IMPUESTO SOBRE LA RENTA",
            "PERSONAS MORALES RÉGIMEN GENERAL",
            "Declaraciones::Página",
            "DECLARACIÓN PROVISIONAL O DEFINITIVA DE IMPUESTOS FEDERALES"
        };
  

        //DATOS DE IDENTIFICACIÓN
        public static string[] labelDatosIdentificacion = { "RFC", "DENOMINACIÓN O\nRAZÓN SOCIAL" };

        //DATOS GENERALES
        public static string[] labelDatosGenerales = {
            "TIPO DE DECLARACIÓN",
            "EJERCICIO",
            "PERIODO",
            "FECHA Y HORA DE\nPRESENTACIÓN",
            "NÚMERO DE\nOPERACIÓN"
        };

        //DETERMINACIÓN DEL IMPUESTO SOBRE LA RENTA
        //PERSONAS MORALES RÉGIMEN GENERAL
        public static string[] labelDeterminacionISR = {
            "SUMA DE INGRESOS NOMINALES DE\nMESES ANTERIORES DEL EJERCICIO",
            "ISR CAUSADO", //2018
            "ESTÍMULOS ACREDITABLES",
            "INGRESOS NOMINALES DEL MES QUE\nDECLARA",
            "REDUCCIONES",
            "TOTAL DE INGRESOS NOMINALES",
            "IMPUESTO DEL PERIODO", "COEFICIENTE DE UTILIDAD",
            "PAGOS PROVISIONALES EFECTUADOS\nCON ANTERIORIDAD",
            "UTILIDAD FISCAL PARA PAGO\nPROVISIONAL",
            "IMPUESTO RETENIDO",
            "INVENTARIO ACUMULABLE", //2018
            "PARTICIPACIÓN DE LOS TRABAJADORES\nEN LAS UTILIDADES",
            "OTRAS CANTIDADES A CARGO DEL\nCONTRIBUYENTE",
            "ANTICIPOS Y RENDIMIENTOS", //2018
            "INVENTARIO ACUMULABLE",
            "OTRAS CANTIDADES A FAVOR DEL\nCONTRIBUYENTE",
            "ANTICIPOS Y RENDIMIENTOS\nDISTRIBUIDOS EN EL PERIODO",
            "DIFERENCIA A CARGO",
            "PÉRDIDAS FISCALES DE EJERCICIOS\nANTERIORES PENDIENTES DE APLICAR",
            "IEPS ACREDITABLE DE ALCOHOL,\nALCOHOL DESNATURALIZADO DE\nPRODUCTOS DISTINTOS DE BEBIDAS\nALCOHÓLICAS",
            "ESTÍMULO FISCAL POR PTU", //2018
            "ESTÍMULO FISCAL POR DEDUCCIÓN\nINMEDIATA",
            "IMPUESTO CORRESPONDIENTE A LA\nPARTICIPACIÓN CONSOLIDABLE",
            "DEDUCCIÓN ADICIONAL DEL FOMENTO\nAL PRIMER EMPLEO",
            "PORCENTAJE DE PARTICIPACIÓN\nCONSOLIDABLE",
            "BASE GRAVABLE DEL PAGO\nPROVISIONAL",
            "IMPUESTO A CARGO",
            "ISR CAUSADO"
        };

        //DETALLE DEL PAGO
        //R1 ISR PERSONAS MORALES
        public static string[] labelR1ISRPERSONASMORALES = {
            "A CARGO",
            "ACREDITAMIENTO SORTEOS", //2018
            "ACREDITAMIENTO SORTEO DE EL BUEN\nFIN",
            "PARTE ACTUALIZADA",
            "DIÉSEL MARINO",
            "RECARGOS",
            "TOTAL DE APLICACIONES",
            "MULTA POR CORRECCIÓN",
            "FECHA DEL PAGO REALIZADO CON\nANTERIORIDAD",
            "TOTAL DE CONTRIBUCIONES",
            "MONTO PAGADO CON ANTERIORIDAD",
            "CRÉDITO AL SALARIO",
            "IMPORTE PAGADO EN LAS ÚLTIMAS 48\nHORAS",
            "SUBSIDIO PARA EL EMPLEO",
            "CANTIDAD A CARGO",
            "IMPUESTO A LOS DEPÓSITOS EN\nEFECTIVO ACREDITABLE",
            "¿APLICA PRIMERA PARCIALIDAD?",
            "COMPENSACIONES",
            "IMPORTE DE LA 1RA. PARCIALIDAD",
            "CRÉDITO IEPS DIÉSEL SECTOR\nPRIMARIO Y MINERO",
            "IMPORTE SIN LA 1RA. PARCIALIDAD",
            "DIÉSEL AUTOMOTRIZ PARA\nTRANSPORTE",
            "CANTIDAD A FAVOR",
            "USO DE INFRAESTRUCTURA\nCARRETERA DE CUOTA",
            "CANTIDAD A PAGAR",
            "OTROS ESTÍMULOS"
        };

        //R13 ISR RETENCIONES POR ASIMILADOS A SALARIOS
        //R14 ISR RETENCIONES POR SERVICIOS PROFESIONALES
        //R18 ISR RETENCIONES POR PAGOS AL EXTRANJERO
        public static string[] labelDetallesPagoR31418 = {
            "A CARGO",
            "ACREDITAMIENTO SORTEOS",
            "PARTE ACTUALIZADA",
            "DIÉSEL MARINO",
            "RECARGOS",
            "TOTAL DE APLICACIONES",
            "MULTA POR CORRECCIÓN",
            "FECHA DEL PAGO REALIZADO CON\nANTERIORIDAD",
            "TOTAL DE CONTRIBUCIONES",
            "MONTO PAGADO CON ANTERIORIDAD",
            "CRÉDITO AL SALARIO",
            "IMPORTE PAGADO EN LAS ÚLTIMAS 48\nHORAS",
            "SUBSIDIO PARA EL EMPLEO",
            "CANTIDAD A CARGO",
            "IMPUESTO A LOS DEPÓSITOS EN\nEFECTIVO ACREDITABLE",
            "¿APLICA PRIMERA PARCIALIDAD?",
            "COMPENSACIONES",
            "IMPORTE DE LA 1RA. PARCIALIDAD",
            "CRÉDITO IEPS DIÉSEL SECTOR\nPRIMARIO Y MINERO",
            "IMPORTE SIN LA 1RA. PARCIALIDAD",
            "DIÉSEL AUTOMOTRIZ PARA\nTRANSPORTE",
            "CANTIDAD A FAVOR",
            "OTROS ESTÍMULOS",
            "CANTIDAD A PAGAR"
        };

        //DETERMINACIÓN DEL IMPUESTO AL VALOR AGREGADO
        //MONTOS DE LOS ACTOS O ACTIVIDADES PAGADOS
        public static string[] labelMontosDeActosoActividadesPagadas = {
            "TOTAL DE LOS ACTOS O ACTIVIDADES\nPAGADOS A LA TASA DEL 16% DE IVA",
            "TOTAL DE LOS ACTOS O ACTIVIDADES\nPAGADOS EN LA IMPORTACIÓN DE\nBIENES Y SERVICIOS A LA TASA DEL 11%\nDE IVA (VIGENTE EN 2013)",
            "TOTAL DE LOS ACTOS O ACTIVIDADES\nPAGADOS A LA TASA DEL 11% DE IVA\n(VIGENTE EN 2013)", //2018
            "TOTAL DE LOS ACTOS O ACTIVIDADES\nSUJETOS AL ESTÍMULO DE LA RFN",
            "TOTAL DE LOS DEMÁS ACTOS O\nACTIVIDADES PAGADOS A LA TASA DEL\n0% DE IVA",
            "TOTAL DE LOS ACTOS O ACTIVIDADES\nPAGADOS EN LA IMPORTACIÓN DE\nBIENES Y SERVICIOS A LA TASA DEL 16%\nDE IVA",
            "TOTAL DE LOS ACTOS O ACTIVIDADES\nPAGADOS POR LOS QUE NO SE PAGARÁ\nEL IVA (EXENTOS)"
        };

        //DETALLE DEL TOTAL DE LOS ACTOS O ACTIVIDADES PAGADOS A LA TASA DEL 16% DE IVA
        public static string[] labelTotalActosoActividadesPagadasTasa16 = {
            "INTERESES PAGADOS A LA TASA DEL\n16%",
            "OTROS ACTOS O ACTIVIDADES\nPAGADOS A LA TASA DEL 16%",
            "REGALÍAS PAGADAS ENTRE PARTES\nRELACIONADAS A LA TASA DEL 16%",
            "TOTAL DE ACTOS O ACTIVIDADES\nPAGADOS A LA TASA DEL 16%"
        };

        //DETERMINACIÓN DEL IMPUESTO AL VALOR AGREGADO ACREDITABLE
        public static string[] labelDeterminacionIVAAcreditable = {
            "TOTAL DE IVA DE ACTOS O ACTIVIDADES\nPAGADOS A LA TASA DEL 16%",
            "IVA TRASLADADO O PAGADO EN LA\nIMPORTACIÓN POR ADQUISICIÓN DE\nBIENES DISTINTOS DE LAS\nINVERSIONES, ADQUISICIÓN DE\nSERVICIOS O POR EL USO O GOCE\nTEMPORAL DE BIENES DESTINADOS\nEXCLUSIVAMENTE PARA REALIZAR\nACTOS O ACTIVIDADES POR LOS QUE\nNO SE ESTÁ OBLIGADO AL PAGO DEL\nIMPUESTO",
            "TOTAL DE IVA DE ACTOS O ACTIVIDADES\nPAGADOS A LA TASA DEL 11% (VIGENTE\nEN 2013)",
            "IVA PAGADO SUJETO AL ESTÍMULO DE\nLA RFN",
            "IVA TRASLADADO O PAGADO EN LA\nIMPORTACIÓN DE INVERSIONES\nDESTINADAS EXCLUSIVAMENTE PARA\nREALIZAR ACTOS O ACTIVIDADES POR\nLOS QUE NO SE ESTÁ OBLIGADO AL\nPAGO DEL IMPUESTO",
            "TOTAL DE IVA DE ACTOS O ACTIVIDADES\nPAGADOS EN LA IMPORTACIÓN DE\nBIENES Y SERVICIOS A LA TASA DEL 16%",
            "IVA DE BIENES UTILIZADOS\nINDISTINTAMENTE PARA REALIZAR\nACTOS O ACTIVIDADES GRAVADOS Y\nACTOS O ACTIVIDADES POR LOS QUE\nNO SE ESTÁ OBLIGADO AL PAGO DEL\nIMPUESTO",
            "TOTAL DE IVA DE ACTOS O ACTIVIDADES\nPAGADOS EN LA IMPORTACIÓN DE\nBIENES Y SERVICIOS A LA TASA DEL 11%\n(VIGENTE EN 2013)",
            "PROPORCIÓN UTILIZADA CONFORME AL\nARTÍCULO 5 DE LA LIVA",
            "TOTAL DE IVA TRASLADADO AL\nCONTRIBUYENTE (EFECTIVAMENTE\nPAGADO)",
            "PROPORCIÓN UTILIZADA CONFORME AL\nARTÍCULO 5-B DE LA LIVA",
            "IVA TRASLADADO POR ADQUISICIONES\nDE BIENES DISTINTOS DE LAS\nINVERSIONES, ADQUISICIÓN DE\nSERVICIOS O POR EL USO O GOCE\nTEMPORAL DE BIENES QUE SE UTILIZAN\nEXCLUSIVAMENTE PARA REALIZAR\nACTOS O ACTIVIDADES GRAVADOS",
            "IVA ACREDITABLE DE BIENES\nUTILIZADOS INDISTINTAMENTE PARA\nREALIZAR ACTOS O ACTIVIDADES\nGRAVADOS Y ACTOS O ACTIVIDADES\nPOR LOS QUE NO SE ESTÁ OBLIGADO AL\nPAGO DEL IMPUESTO",
            "IVA PAGADO EN LA IMPORTACIÓN POR\nADQUISICIÓN DE BIENES DISTINTOS DE\nLAS INVERSIONES, ADQUISICIÓN DE\nSERVICIOS O POR EL USO O GOCE\nTEMPORAL DE BIENES QUE SE UTILIZAN\nEXCLUSIVAMENTE PARA REALIZAR\nACTOS O ACTIVIDADES GRAVADOS",
            "IVA ACREDITABLE",
            "IVA TRASLADADO POR LA ADQUISICIÓN\nDE INVERSIONES DESTINADAS\nEXCLUSIVAMENTE PARA REALIZAR\nACTOS O ACTIVIDADES GRAVADOS",
            "MONTO ACREDITABLE ACTUALIZADO A\nINCREMENTAR DERIVADO DEL AJUSTE",
            "IVA PAGADO POR LA IMPORTACIÓN DE\nINVERSIONES DESTINADAS\nEXCLUSIVAMENTE PARA REALIZAR\nACTOS O ACTIVIDADES GRAVADOS",
            "IVA PAGADO POR LA IMPORTACIÓN DE\nINVERSIONES DESTINADAS", //2018
            "TOTAL DE IVA ACREDITABLE DEL\nPERIODO",
            "TOTAL DE IVA CORRESPONDIENTE A\nACTOS O ACTIVIDADES GRAVADOS"
        };

        //DETERMINACIÓN DE IMPUESTO AL VALOR AGREGADO
        public static string[] labelDetermionacionIVA = {
            "VALOR DE LOS ACTOS O ACTIVIDADES\nGRAVADOS A LA TASA DEL 16%",
            "OTRAS CANTIDADES A FAVOR DEL\nCONTRIBUYENTE",
            "VALOR DE LOS ACTOS O ACTIVIDADES\nGRAVADOS A LA TASA DEL 11%\n(VIGENTE EN 2013)",
            "CANTIDAD A CARGO",
            "VALOR DE LOS ACTOS O ACTIVIDADES\nGRAVADOS A LA TASA DEL 0%\nEXPORTACIÓN",
            "SALDO A FAVOR",
            "VALOR DE LOS ACTOS O ACTIVIDADES\nGRAVADOS A LA TASA DEL 0% OTROS",
            "DEVOLUCIÓN INMEDIATA OBTENIDA",
            "SUMA DE LOS ACTOS O ACTIVIDADES\nGRAVADOS",
            "SALDO A FAVOR DEL PERIODO",
            "VALOR DE LOS ACTOS O ACTIVIDADES\nPOR LOS QUE NO SE DEBA PAGAR EL\nIMPUESTO (EXENTOS)",
            "ACREDITAMIENTO DEL SALDO A FAVOR\nDE PERIODOS ANTERIORES (SIN\nEXCEDER DE LA CANTIDAD A CARGO)",
            "IMPUESTO CAUSADO",
            "DIFERENCIA A CARGO",
            "CANTIDAD ACTUALIZADA A\nREINTEGRARSE DERIVADA DEL AJUSTE",
            "IEPS ACREDITABLE DE ALCOHOL,\nALCOHOL DESNATURALIZADO DE\nPRODUCTOS DISTINTOS DE BEBIDAS\nALCOHÓLICAS",
            "IVA RETENIDO AL CONTRIBUYENTE",
            "IMPUESTO A CARGO",
            "TOTAL DE IVA ACREDITABLE",
            "REMANENTE DE SALDO A FAVOR IEPS\nACREDITABLE DE ALCOHOL, ALCOHOL\nDESNATURALIZADO DE PRODUCTOS\nDISTINTOS DE BEBIDAS ALCOHÓLICAS",
            "OTRAS CANTIDADES A CARGO DEL\nCONTRIBUYENTE"
        };

        //DETALLE DEL VALOR DE LOS ACTOS O ACTIVIDADES GRAVADOS A LA TASA DEL 16%
        public static string[] labelDetalleActosoActGrabadasTasa16 = {
            "INTERESES COBRADOS A LA TASA DEL\n16%",
            "OTROS ACTOS O ACTIVIDADES\nGRAVADOS A LA TASA DEL 16%",
            "REGALÍAS ENTRE PARTES\nRELACIONADAS A LA TASA DEL 16%",
            "TOTAL DE LOS ACTOS O ACTIVIDADES\nGRAVADOS A LA TASA DEL 16%"
        };

        //R21 IMPUESTO AL VALOR AGREGADO
        public static string[] labelR21_IVA = {
            "A CARGO",
            "CERTIFICADOS TESOFE",
            "A FAVOR",
            "DIÉSEL MARINO",
            "PARTE ACTUALIZADA",
            "TOTAL DE APLICACIONES",
            "RECARGOS",
            "FECHA DEL PAGO REALIZADO CON\nANTERIORIDAD",
            "MULTA POR CORRECCIÓN",
            "MONTO PAGADO CON ANTERIORIDAD",
            "TOTAL DE CONTRIBUCIONES",
            "IMPORTE PAGADO EN LAS ÚLTIMAS 48\nHORAS",
            "CRÉDITO AL SALARIO",
            "CANTIDAD A CARGO",
            "SUBSIDIO PARA EL EMPLEO",
            "¿APLICA PRIMERA PARCIALIDAD?",
            "COMPENSACIONES",
            "IMPORTE DE LA 1RA. PARCIALIDAD",
            "DIÉSEL AUTOMOTRIZ PARA\nTRANSPORTE",
            "IMPORTE SIN LA 1RA. PARCIALIDAD",
            "USO DE INFRAESTRUCTURA\nCARRETERA DE CUOTA",
            "CANTIDAD A FAVOR",
            "OTROS ESTÍMULOS",
            "CANTIDAD A PAGAR"
        };

        //DETALLE DEL PAGO
        //R24 IVA RETENCIONES
        public static string[] labelR24IVARETENCIONES = {
            "A CARGO",
            "DIÉSEL MARINO",
            "PARTE ACTUALIZADA",
            "TOTAL DE APLICACIONES",
            "RECARGOS",
            "FECHA DEL PAGO REALIZADO CON\nANTERIORIDAD",
            "MULTA POR CORRECCIÓN",
            "MONTO PAGADO CON ANTERIORIDAD",
            "TOTAL DE CONTRIBUCIONES",
            "IMPORTE PAGADO EN LAS ÚLTIMAS 48\nHORAS",
            "CRÉDITO AL SALARIO",
            "CANTIDAD A CARGO",
            "SUBSIDIO PARA EL EMPLEO",
            "¿APLICA PRIMERA PARCIALIDAD?",
            "COMPENSACIONES",
            "IMPORTE DE LA 1RA. PARCIALIDAD",
            "CRÉDITO IEPS DIÉSEL SECTOR\nPRIMARIO Y MINERO",
            "IMPORTE SIN LA 1RA. PARCIALIDAD",
            "OTROS ESTÍMULOS",
            "CANTIDAD A FAVOR",
            "CERTIFICADOS TESOFE",
            "CANTIDAD A PAGAR"
        };
    }
}
